spring.application.name=productapi

server.port=${PORT:8080}
#=====Banco de Dados=====
spring.jpa.show-sql=true


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# CREATE TABLE IF NOT EXISTS public.produtos
# (
#     id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
#     codigo character varying(255) COLLATE pg_catalog."default" NOT NULL,
#     nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
#     descricao character varying(255) COLLATE pg_catalog."default",
#     preco numeric(38,2) NOT NULL,
#     quantidade integer NOT NULL,
#     data_criacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
#     CONSTRAINT produtos_pkey PRIMARY KEY (id),
#     CONSTRAINT produtos_codigo_key UNIQUE (codigo),
#     CONSTRAINT produtos_nome_key UNIQUE (nome),
#     CONSTRAINT produtos_quantidade_check CHECK (quantidade >= 0),
#     CONSTRAINT produtos_preco_check CHECK (preco >= 0::numeric)
# )